services:
  - type: web
    name: url-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
           - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
